### PR TITLE
fixes music search

### PR DESCRIPTION
**Pull request by chalda**

### CODE REVIEW

**Comment by chalda** [comment]
@Einarin so there is an issue where the bot will prematurely end songs. i still think the issue is that youtubeDL finishes to download the song and thus ends the readablestream. the way around this is to buffer the stream (like write it to disk) and make another readable stream reading the file off of the disk. but id really rather not write to disk at all. not entirely sure how to stream into memory alone

**Comment by Androz2091** [comment]
I have the same problem with my bot. The song stops before the end...

**Comment by chalda** [comment]
holy crap @Androz2091 just peeked your github page. really like the dashboard for AtlantaBot. ive been meaning to make something like that to help with configuration and to host things like top played songs/play history or other plugin specific datas.
i think ultimately there are 2 solutions: 

1) switch to a more node-native youtube-dl lib like ytdl-core. however it seems that it only has support for youtube at the moment and i really like the idea of supporting wide range of music hosting. in general the core youtube-dl is much more powerful as it can handle live-streams, youtube playlists etc

2) i definitely think there is a way to do this well with node.js Streams apis but i know nothing about them really apart from streaming files.

realistically speaking i could stream the song to disk and then get a readable stream of the file which is sent into discord but i am not a fan of having to intermediately store the file. my personal bot runs on an Rpi-2 which runs raspian of of an SD card. I dont know how much of a bottle neck this would create on the i/o.

ideally the entirely operation would happen in-memory and i think you can also do this with streams. Stream youtube-dl file into a Duplex stream while reading from the stream into discord. The one potentially issue with this solution is RAM. my R-pi has 1 gig of ram, a 1 hour youtube video would likely be quite large.

**Comment by Androz2091** [comment]
I'm not keen on writing on the disk either....
However, I already use ytdl core and it doesn't work either (the music ends early). It was working very well before and when I switched to the Master version of Discord.js by updating almost all the dependencies, I had this problem.
I'll try to change some versions to see if it's better but I don't really have time these next few weeks....

**Comment by chalda** [comment]
@Androz2091 @Einarin check my latest commit. taken directly from ytdl-core code and adapted to work with normal youtube-dl

**Pull request merged**
