### PR TITLE
preload plugin modules

### PR DESCRIPTION
**Pull request by Devlix**
Installs the required modules for the plugins before trying to load them through the package.json "dependencies" located in each of the plugin folders. This makes the plugins easier to install as the user would not have to worry about adding modules to the project.

### CODE REVIEW

**Comment by chalda** [comment]
I like it been meaning to implement something like this since the project
started. Thanks man! There even was a ticket for this somewhere.

**Comment by chalda** [comment]
did you actually move the plugins out btw? Also you removed the requests dep?

**Comment by Devlix** [comment]
The plugins are still there and the request dep should get installed because it is a dependency in the plugins/images/package.json

**Comment by chalda** [comment]
ah gotcha. didnt see that :D 
tell you what ill take this even further tomorrow. separate that monster command block from main. i am thinking put a plugin.js file in each folder and have that define the plugins. then to add/remove plugins you can just unpack them in the plugins folder, or zip/remove them to take them out.

**Comment by Devlix** [comment]
Yeah ideally I would imagine we would have no commands in the main file and try to group the existing ones into plugins. I feel we need to handle permissions for certain things in the main file though like probably overwrite the existing ban and kick functions to check the permissions of the message author.

**Comment by chalda** [comment]
I have some idea how this could work. Another feature I wanna add needs
some persistence so I'll see what we can do.

**Comment by Devlix** [comment]
Hey so maybe we should turn this branch into the plugin feature branch and go through the requirements before merging. I can separate the existing functionality into a plugin.js so it is easier to work on and merge later.

**Comment by Devlix** [comment]
So I moved that functionality over in ce14ba4 I also added something in there that searches the plugins for certain function like banMember etc. and it will disable the plugin by default and warn the owner about it until it is allowed in options.json. Let me know what you think about that.

**Comment by Devlix** [comment]
Alright so I got rid of the plugin blocking and I added the code needed to load plugins for an Electrify build if we are to use that, only tested on a Windows build though.

**Comment by Devlix** [comment]
So I want to go ahead and merge this then I have some stuff for creating electron builds.

**Pull request merged**
