### PR TITLE
Add command to set presence

### LINKED ISSUE #168: allow customizing bot's presence status
set here: https://github.com/chalda/DiscordBot/blob/5111d5f57abbeca73c551d34b263adae5e62ea62/discord_bot.js#L272
keep that as default and allow overriding to a string with ohter settings?

### PR DESCRIPTION
**Pull request by NicWebster96**
Ability to set presence of the bot. If the user does not provide a string after the command, set it to the default presence text.
Closes #168

### CODE REVIEW

**Comment by chalda** [comment]
fine with me, except i would want to see this be controlled by permissions json. too much room for trolling if anyone in the server can modify the presence setting

**Comment by NicWebster96** [comment]
> fine with me, except i would want to see this be controlled by permissions json. too much room for trolling if anyone in the server can modify the presence setting

Agreed. Added presence to false be default in permissions. Let me know if there is a different approach I should take for this

**Comment by F9Alejandro** [comment]
Don't see an issue with this and it replaces the old code that was once there.

**Comment by Einarin** [comment]
Looks good to me too. Merging.

**Pull request merged**
