### PR TITLE
Added support for logging in with a bot account

### PR DESCRIPTION
**Pull request by Einarin**
Updated discord.js dependency to 7.0

### CODE REVIEW

**Comment by DerfOh** [comment]
:+1: Been looking forward to this. Great work!

**Comment by Dog2puppy** [comment]
:) Needs merged!

**Comment by DerfOh** [comment]
Tested and working :+1:  also I found [this article](https://github.com/reactiflux/discord-irc/wiki/Creating-a-discord-bot-&-getting-a-token) to be very helpful, maybe add it to the docs once this is merged :smile:

**Comment by Einarin** [comment]
I can't believe this has been sitting here this long. Merged now.

**Pull request merged**
