### PR TITLE
Plugins

### PR DESCRIPTION
**Pull request by Devlix**
Hey guys so I put this together as a potential way of doing the plugins. Plugins are loaded from the the `plugins` folder like node modules. I converted the `!image` command to be here and also added `!ggif` command in there to show how multiple commands in a plugin could be done. This also works alongside the way it's been done previously so the plugin commands still work with `!help` the same way. Let me know if you had a different idea of doing this or how to improve this, thanks.

### CODE REVIEW

**Comment by chalda** [comment]
Did you push this to master? Someone just pinged on reddit that their
deployment is failing, can't find module wolfram.

From reddit:
When I try to "node discord_bot.js" I get the following error :
http://i.imgur.com/aCKuP4v.png

I there was also a bunch of errors at the npm install even after following
the instructions on the github instructions link :O

-------

I started working on a plugin parsing structure as well that would a worked
approximately the same way. This feels pretty straightforward so we prolly
have something very similar which means either will work :)

**Comment by Devlix** [comment]
No this has not been pushed to master, it looks like his problem is whatever the issue is with his npm install because he never got the wolfram node module.

**Comment by chalda** [comment]
Ah OK looking at it now that would make sense lol. I was away most if the
weekend. Just briefly took a look at a reddit notification.

**Comment by Devlix** [comment]
Yeah and actually a system like this should allow the bot to still start even if there is a problem with a certain plugin, but I want to figure out how to make `npm install` also include the plugins folder so it installs the dependencies the plugins require.

**Comment by chalda** [comment]
Fuck that would be a good idea. And disable a plugin if it's not correctly
setup (missing keys or requiremenrs) but this is now beginning to sound
very complicated heh

**Comment by chalda** [comment]
ugh prolly easiest way to do mass mail.
few things:

there is a discord server for API discussions:
https://discordapp.com/channels/81384788765712384/81384788765712384
the guy who wrote discord.js is there, asked him the progress on voice he
said they are working on it

related another guy has a 3rd JS discord api lib, he has voice
encoding/decoding working!!!!!!
https://github.com/qeled/discordie/blob/master/lib/voice/threading/DecoderWorker.js

**Comment by DerfOh** [comment]
I had problems with getting the correct key from Wolfram after setting up an account with their api service. I ended up commenting out the wolfram section of the code and things seemed to work fine afterwords.

**Comment by Einarin** [comment]
I went ahead and merged this, as it seems like a good idea to get some real infrastructure in place. Thanks for doing this @Devlix! Unfortunately Google shut down the google images api, so the commands don't actually work any more. See #15

**Pull request merged**
